### ISSUE TITLE
Idea about tab character check

### ISSUE THREAD

**Issue by ychulovskyy** [CodeNarc/CodeNarc#135]
There is a need to check that there is no tab character in source code.
Actually, IllegalString rule allows to check this but it's not obvious.
What about the options:
1. Create IllegalTabCharacter rule that will be copy of IllegalString rule but has illegal string hardcoded
or
2. Update IllegalString documentation and StarterRuleSet (via updating codenarc-rule-extrainfo.properties) with the following:
    ruleset('rulesets/generic.xml') {
        IllegalString(name:'IllegalTabCharacter', string:'	', violationMessage: 'tab character is not allowed')
    }
or
3. your option :)

P.S.: Does it make sense to add the rule into RunCodeNarcAgainstProjectSourceCode.ruleset?

**Comment by chrismair** [comment]
Good idea. I think a new rule would be appropriate. We use "Illegal" for the generic rules, so I think "TabCharacter" would be a reasonable name, and consistent with how we named most other rules.

This should be in the "convention" package/ruleset, since some teams prefer to use tabs.

And yes, this could be added to "RunCodeNarcAgainstProjectSourceCode.ruleset".

Thanks.

**Comment by chrismair** [comment]
Before beginning implementation of this rule, let me clean up the source files. I temporarily added a rule to RunCodeNarcAgainstProjectSourceCode in my workspace, and it came up with over a hundred violations. I just want to be sure that those are legitimate violations, rather than flagging something that would make the rule impractical, at least that simplistic implementation.

**Comment by chrismair** [comment]
I have cleaned up the rogue tab characters in the source files. There were a lot. But they were all "legitimate" violations -- nothing weird or surprising.

If no one else steps forward to create the TabCharacter rule, I'll probably do it myself in a week or so.

**Comment by chrismair** [comment]
I am also open to calling this rule NoTabCharacter, if preferred. We haven't always been consistent about rule naming conventions, and we do have a couple other NoXxx rules.

**Comment by chrismair** [comment]
Available in CodeNarc 0.25.
