### ISSUE TITLE
False positive GetterMethodCouldBeProperty when anonymous inner class is returned.

### ISSUE THREAD

**Issue by Jcamilorada** [CodeNarc/CodeNarc#168]
When a constant value is retrieved as part of anonymous inner class return type GetterMethodCouldBeProperty violation is raised. Please review following scenario.

```
interface IResult {
    int getIntValue()
}

class MyClass {
    private static final int CONSTANT_RESULT = 5

    IResult operate(int parameter) {
        return new IResult() {
            @Override
            int getIntValue() {
                CONSTANT_RESULT
            }
        }
    }
}
```

Please note that if return statement is included not violation is raised due the implement rule logic.  I already created  [pr](https://github.com/CodeNarc/CodeNarc/pull/167/commits/a3187701d63d4236c5266f41a30a06026a75d2f5) with unit test and rule update.

**Comment by chrismair** [comment]
I do not think that is a false positive. The violation that you get is valid. Your code example could be changed to the following to avoid the violation:

```
       IResult operate(int parameter) {
            return new IResult() {
                int intValue = CONSTANT_RESULT
            }
```

**Comment by Jcamilorada** [comment]
ok do not agree but definitely you have a better a idea of rule purpose.  Please note that violation is not raised if return statement is added so that does not look consistent for me.

```
interface IResult {
    int getIntValue()
}

class MyClass {
    private static final int CONSTANT_RESULT = 5

    IResult operate(int parameter) {
        return new IResult() {
            @Override
            int getIntValue() {
                return CONSTANT_RESULT
            }
        }
    }
}
```

**Comment by chrismair** [comment]
Okay, I agree that the inconsistency between an implicit and explicit return is a bug. I can look into that.

Now I am not saying that you should (always) prefer the one-line property to the full method definition. I was just saying that because that Groovy-ism is applicable in that situation, that the rule violation was valid. In fact, I think that using a property is much less obvious that you are overriding/implementing a method, so I might prefer using a method with @Override, at the cost of those two extra lines of code. I am tempted to add a flag to that rule to allow ignoring methods annotated with @Override.

**Comment by chrismair** [comment]
I fixed the inconsistency in the behavior of GetterMethodCouldBeProperty (with and without a **return**). That will be available in the next release. Thanks.
