### ISSUE TITLE
Variable declared and not used

### ISSUE THREAD

**Issue by fkluthe** [CodeNarc/CodeNarc#223]
Imagine this Groovy-codeblock:

```
def a_renamed = "a"
a_renamed = "only assigned"

def really_used = a + "b"
...
```

I expect codeNarc to find 2 Issues:
1. a_renamed is declared and not used
2. Cannot resolve symbol 'a'

Neither is happening.

**Comment by chrismair** [comment]
1. Yes, I guess that scenario is not currently handled by the [UnusedVariable](http://codenarc.sourceforge.net/codenarc-rules-unused.html#UnusedVariable) rule, since it does count that assignment as a reference.

2. CodeNarc intentionally does not try to process source code that does not compile. Most CodeNarc rules rely on the Groovy AST. Processing invalid source code would require re-implementing an entire Groovy language parser, and one that ignored compile errors.

**Comment by fkluthe** [comment]
All right, thanks for your reply. Are there plans to cover the first scenario?

**Comment by chrismair** [comment]
I have implemented the change to that rule to no longer consider an assignment to a variable a reference.
