### ISSUE TITLE
Fail execution in case of compilation error

### ISSUE THREAD

**Issue by nam-truong-le** [CodeNarc/CodeNarc#269]
In case of compilation error, the command line execution still finishes successfully. Is there any option to fail the execution in this case?

**Comment by chrismair** [comment]
No, not currently.

**Comment by allanlewis** [comment]
I also noticed that compilation errors are included in the `console` report but not in the `text` or `html` reports. My current solution is to write the `console` report to a file and `grep` that for "Compilation failed". This clearly isn't great, so in future I might just use `groovyc` directly at this stage.

**Comment by modestukasai** [comment]
For me it is the same:
`https://github.com/modestukasai/java-9-groovy-with-codenarc`
```
Compilation failed for [CustomCompilerPhaseSourceDecorator[SourceFile[/home/travis/build/modestukasai/java-9-groovy-with-codenarc/src/main/groovy/com/modzo/codenarc/IndexController.groovy]]].
```

```
https://api.travis-ci.org/v3/job/352376366/log.txt
```

**Comment by chrismair** [comment]
It was a fundamental design decision of CodeNarc to assume that the code being analyzed is valid Groovy. CodeNarc relies very heavily on the Groovy AST, which will not work if the Groovy code being analyzed is invalid. It may make sense to compile the Groovy code as a first step in your workflow, especially if you are doing this as part of continuous integration.

@modestukasai: A common cause of those errors is enabling CodeNarc enhanced rules when the CodeNarc classpath does not include the jars required by the application code being analyzed. See http://codenarc.sourceforge.net/codenarc-enhanced-classpath-rules.html.

**Comment by chrismair** [comment]
The compilation failure applies to a source file, rather than a rule. Once that source file fails compilation, no rules will be applied to it (at least no rules that use the AST at that same compiler phase). It would be challenging to log the rule that triggered the initial compilation of that source file, since that is decoupled.

I have enhanced the "compilation failed" error message to add a `toString()` of the exception that caused it, thus typically including compilation error information.

If there is significant support for the original question about terminating CodeNarc when there are compilation errors, we can consider that, though I think that will be non-trivial to implement. Please open a separate issue in that case.
