### ISSUE TITLE
UnnecessaryGString rule not ignored in Baseline

### ISSUE THREAD

**Issue by tmysik** [CodeNarc/CodeNarc#303]
Report based on discussion in issue #282.

If one generates [Baseline report](http://codenarc.sourceforge.net/codenarc-BaselineXmlReportWriter.html) and runs CodeNarc with it (without any changes to the source code), some `UnnecessaryGString` violations can appear even if there should not be any. In our case, this happens for strings like e.g.:

* `"Guaraní"`
* `"75%–84%"`
* `"Tschüß"`
* `"…"`
* `"str\n\r"`

Thank you.

**Comment by chrismair** [comment]
What exactly do you mean by:
> some UnnecessaryGString violations can appear even if there should not be any

Are you saying that:
1. You have the above strings in double quotes in your code and get *UnnecessaryGString* violations when you run without the *excludeBaseline*, as expected. You expect that violation to be hidden when you do use *excludeBaseline*, but it still appears.

2. You have the above strings in single quotes in your code and only when you set the *excludeBaseline* to use the baseline report, then new and incorrect *UnnecessaryGString* violations occur?

**Comment by chrismair** [comment]
I'm assuming your situation was number 1 above.

At first I figured the issue was related to the replacement of special characters when writing that baseline report. But I was able to eventually reproduce your issue and it turns out it was due to the encoding of the XML file. I changed to "UTF-8" and was able to resolve the issue. The only wrinkle is that the behavior of the "\r" within a string still caused problems; I *think* that is because I am running on Linux, but we'll see.

**Comment by tmysik** [comment]
Sorry for the delay - the point `2` is correct. Exact steps are:

* have one of the string I provided in the initial description in your code
* generate Baseline report
* run CodeNarc with the generated Baseline report

Expected: no violation occurs
Actual: `UnnecessaryGString` violation is reported

HTH, thank you.

**Comment by tmysik** [comment]
BTW I am on Linux as well.

**Comment by chrismair** [comment]
I addressed the \r issue as well.

Available in CodeNarc v1.1.
