### ISSUE TITLE
UnnecessaryPackageReference false-positive

### ISSUE THREAD

**Issue by boris-petrov** [CodeNarc/CodeNarc#353]
```groovy
def files = new java.io.File(path).listFiles()
```

This code gives a `Specifying the package name is not necessary for java.io.File` warning however this is wrong, as it is in a package in which I've got another `File` class.

**Comment by chrismair** [comment]
I agree that it "should not" have a violation in that case. 

But given that is a relatively simple rule, which does not have visibility to the classpath, my initial thought is that I'd be hesitant to try to address this corner case.

**Comment by fenuks** [comment]
I have same issue, although in my case, another class named `File` is imported, so I think rule should be able to check that before reporting violation.

**Comment by chrismair** [comment]
> I have same issue, although in my case, another class named `File` is imported, so I think rule should be able to check that before reporting violation.

I looked into implementing the check for the `File` class and classes like that, but it ends up not being feasible with the rule's current design. It is going off auto-imported packages, such as `java.io` and 'java.util', rather than explicitly checking for the individual class names within those packages, so the rule does not "know" that the File class is auto-imported, just that the `java.io` package is. The rule cannot see that your `File` class conflicts with the `java.io.File` class.

I think your best option is to disable the rule for those specific, problematic classes.

**Comment by fenuks** [comment]
I did just that, thank you.
