### ISSUE TITLE
Executable codenarc-x.yy.jar

### ISSUE THREAD

**Issue by rowlap** [CodeNarc/CodeNarc#457]
Please add Main-Class config so that the codenarc jar file can be executed directly. (Not entirely sure where this set is in build.gradle or elsewhere, but the functional equivalent of the `jar e` option.)

**Comment by chrismair** [comment]
I can easily update the `build.gradle` to add the `CodeNarc` main class:
```
    Manifest-Version: 1.0
    Main-Class: org.codenarc.CodeNarc
```

But when you try to run that using `java -jar CodeNarc-1.5.jar`, you get:
```
    Error: Could not find or load main class org.codenarc.CodeNarc
    Caused by: java.lang.NoClassDefFoundError: groovy/lang/GroovyObject
```
even if you copy the Groovy jar to the same dir and specify `java  -classpath groovy-2.4.17.jar -jar CodeNarc-1.5.jar` because  (https://javarevisited.blogspot.com/2011/01/how-classpath-work-in-java.html):

> It's also worth noting that when you use the  java -jar command line option to run your Java
> program as an executable JAR, then the CLASSPATH environment variable will be ignored, and 
> also the -cp and -classpath switches will be ignored.

Now I can also have Gradle add the dependent jars to the manifest file:
```
  Manifest-Version: 1.0
  Class-Path: groovy-ant-2.4.17.jar groovy-groovydoc-2.4.17.jar groovy-templates-2.4.17.jar groovy-xml-2.4.17.jar groovy-2.4.17.jar slf4j-api
   -1.7.25.jar GMetrics-1.0.jar ant-junit-1.9.4.jar ant-1.9.4.jar ant-launcher-1.9.4.jar ant-antlr-1.9.4.jar
  Main-Class: org.codenarc.CodeNarc
```

But that then *requires* that all of those jars exist in the same directory, which seems like an impractical limitation.

So I am not sure there is much value with implementing this, unless I am missing something.

**Comment by rowlap** [comment]
Fair enough - I didn't appreciate the interaction with `java -jar ...` and other libraries.
