### ISSUE TITLE
!instanceof operator not supported

### ISSUE THREAD

**Issue by rkrisztian** [CodeNarc/CodeNarc#564]
Please add support for the `!instanceof` operator, right now the Gradle codenarc plugin fails to compile my main code if it includes that operator, even though I am using Groovy 3 and CodeNarc version 1.6.1.

**Comment by chrismair** [comment]
Please provide some sample code that is failing, as well as the compiler error message.

**Comment by rkrisztian** [comment]
Sample code: ```groovy
		def dog = new Dog()
		println GroovySystem.version
		if (dog !instanceof Animal) {
			println 'That is weird.'
		}
		else {
			println 'That is right.'
		}
```

Full demo here: https://github.com/rkrisztian/testProject
Error: ```none
rkrisztian@linux:~/IdeaProjects/testProject$ gw clean build run --continue
Using gradle at '/home/rkrisztian/IdeaProjects/testProject/gradlew' to run buildfile '/home/rkrisztian/IdeaProjects/testProject/build.gradle':

> Task :clean
> Task :compileJava NO-SOURCE
> Task :compileGroovy
> Task :processResources NO-SOURCE
> Task :classes
> Task :jar
> Task :startScripts
> Task :distTar
> Task :distZip
> Task :assemble
Compilation failed for [SourceFile[/home/rkrisztian/IdeaProjects/testProject/src/main/groovy/Test.groovy]]; org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
None: 5: expecting ')', found '!' @ line 5, column 11.
                if (dog !instanceof Animal) {
             ^

1 error
.
> Task :codenarcMain
> Task :codenarcTest NO-SOURCE
> Task :compileTestJava NO-SOURCE
> Task :compileTestGroovy NO-SOURCE
> Task :processTestResources NO-SOURCE
> Task :testClasses UP-TO-DATE
> Task :test NO-SOURCE
> Task :check
> Task :build

> Task :run
3.0.3
That is right.
```

**Comment by erdi** [comment]
I'm afraid you are not using Groovy 3 for CodeNarc analysis, you are using whatever Groovy version CodeNarc 1.6.1 depends on. To use Groovy 3 for CodeNarc compilation you need to add it to `codenarc` dependency configuration and it can be done by adding the following to your dependencies block:
```
codenarc 'org.codehaus.groovy:groovy-all:3.0.3'
```

**Comment by rkrisztian** [comment]
Well yeah that's embarrassing. I'm wondering why it is so easy to screw that up though:

* https://docs.gradle.org/current/userguide/codenarc_plugin.html#sec:codenarc_dependency_management => Explains the `codenarc` dependency configuration, but no examples like ... oh yeah, Groovy too.
* https://docs.gradle.org/current/dsl/org.gradle.api.plugins.quality.CodeNarcExtension.html => Kinda hard to notice the link to it, by the way, has `toolVersion` but not `groovyVersion`. Doesn't matter, because I didn't even notice `toolVersion` to begin with.
* Usage does not explicitly say that we shouldn't just blindly trust that codeNarc will get the deps right.
* I'm just simply stupid. Yeah, say it.

**Comment by erdi** [comment]
> https://docs.gradle.org/current/userguide/codenarc_plugin.html#sec:codenarc_dependency_management => Explains the codenarc dependency configuration, but no examples like ... oh yeah, Groovy too.

Because usually, it's not needed. Usually the Groovy version that CodeNarc depends on is close enough to the version you are using to compile your code. It only matters if you go across the line of minor or major versions where new syntax might be introduced and you might see compilation errors.

> Usage does not explicitly say that we shouldn't just blindly trust that codeNarc will get the deps right.

It's not CodeNarc that is getting the dependencies wrong or right. It's your build configuration that is not correct. CodeNarc just runs with whatever Groovy you put on the classpath which is what can be controlled via the `codenarc` dependency configuration in a Gradle build. And because CodeNarc specifies a dependency on Groovy in its pom then that's what Gradle will use unless you tell it otherwise.

> I'm just simply stupid. Yeah, say it.

I don't think you are stupid. You just hit a use case which is not what the default configuration of Gradle plugin for CodeNarc is geared towards.

> or give better hints in the documentation.

That would most likely be Gradle's documentation and not CodeNarc's as you are using a plugin that ships with Gradle.

**Comment by erdi** [comment]
Btw, thanks for providing the sample project you had the problem on. It made it very easy for me to see what is going on instead of just guessing.

**Comment by rkrisztian** [comment]
OK, thank you. Opened https://github.com/gradle/gradle/issues/14853 . Sorry for my mistake.
