### ISSUE TITLE
"Compilation failed" displayed for correct Groovy 3 code

### ISSUE THREAD

**Issue by pbielicki** [CodeNarc/CodeNarc#616]
We recently saw in our console logs something worrying:
```
Compilation failed for [SourceFile[/Users/pbielicki/dev/git_clones/gradle-sandbox/codenarc-groovy3/src/main/groovy/example/Test.groovy]]; org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
None: 10: unexpected token: @ @ line 10, column 5.
       @Annotation(condition = { int number ->
       ^

1 error
```

At first we thought it's a Groovy 3 compiler error that is ignored but after little investigation it turned out that this message comes from Codenarc. Here's the reproducer project: https://github.com/britter/gradle-sandbox/tree/main/codenarc-groovy3. To reproduce the problem just run `./gradlew codenarcMain`. If you run `./gradlew compileGroovy` everything will be compiled without any error.

Codenarc doesn't like `&&` at the beginning of the line - see: 
```groovy
@Annotation(condition = { int number ->
    number > 30
    && number < 80
})
static void main(String[] args) {
}
```

**Comment by chrismair** [comment]
My first guess would be that the plugin is running CodeNarc with its defined Groovy dependency, which is Groovy 2.5, and you'd have to override the Groovy version that it uses.

**Comment by pbielicki** [comment]
Indeed: https://scans.gradle.com/s/6chbndnwzjk7i/dependencies?dependencies=groov&expandAll 
I'll try to change it

**Comment by pbielicki** [comment]
@chrismair OK we see Groovy 2.5.12 because Codenarc is implemented using this version. But that doesn't mean it's not able to scan Groovy 3.x code.

**Comment by erdi** [comment]
@pbielicki - as part of the analysis CodeNarc has to partially compile (up to a certain compilation phase depending on what is required by the rules used) the analysed sources. When using CodeNarc via Gradle that partial compilation will happen using whatever groovy version is on the runtime classpath which is defined using the `codenarc` dependency configuration. Personally I always make sure that whatever Groovy version is on the compilation classpath for the project is also used in the `codenarc` configuration otherwise you are likely to hit compilation errors like you have. As far as I know @chrismair tests CodeNarc with Groovy 3.x on the runtime classpath so you should be fine to use that version as part of your `codenarc` dependency configuration.

**Comment by pbielicki** [comment]
@erdi 
> whatever groovy version is on the runtime classpath which is defined using the codenarc dependency configuration

How can I configure that? Ref: https://github.com/britter/gradle-sandbox/tree/main/codenarc-groovy3

**Comment by erdi** [comment]
The Gradle plugin for CodeNarc [adds a dependency configuration called `codenarc`](https://docs.gradle.org/current/userguide/codenarc_plugin.html#sec:codenarc_dependency_management) - you just need to configure it with the the same version of Groovy as the one you use for compilation.  So, in the example you linked to it would be a matter of adding the following to the `dependencies` block.

```
    codenarc("org.codenarc:CodeNarc:2.1.0")
    codenarc("org.codehaus.groovy:groovy-all:3.0.8")
```

**Comment by pbielicki** [comment]
👍  awesome - I'll try to use that in the bigger scale

**Comment by pbielicki** [comment]
actually this works even better:
```
codenarc(platform("org.codehaus.groovy:groovy-bom:3.0.8"))
```

thanks @marcphilipp for the tip
