### ISSUE TITLE
Suggestion for `SpaceAroundMapEntryColon` default configuration

### ISSUE THREAD

**Issue by rkrisztian** [CodeNarc/CodeNarc#625]
I understand that we can configure a rule however we want. But this default just don't make enough common sense to me, and I think we might be doing harm rather than good to the community on the Internet. Here is the reason why:

Why not request a space after a colon? Just as we put a space after a comma, a colon, out of consistency (for one reason), should be indifferently treated. But more importantly, I would not find a code with no space after a colon easy to read, but probably for an other reason than that a colon is somewhat similar to a dot, although easier to differentiate than a dot from a comma. Whatever the reason is, it has to do with the English language.

```groovy
'SpaceAroundMapEntryColon' characterAfterColonRegex: /\s/
```

See also this style guide where I see spaces after colon:
https://groovy-lang.org/style-guide.html

I totally don't mind the default for the "before colon" setting, because vertical alignments cause commit noise problems, and people using tabs for vertical alignment make it even worse. That should not happen.

**Comment by chrismair** [comment]
Your desired style isn't "wrong", but neither is the current default setting. If we were creating this rule today, we might very well choose a different default style, but I don't plan to change the default because:
 - It could be a breaking change for a bunch of teams (where "bunch" is somewhere between 1 and 1M).
 - The current default setting is not "wrong"
 - It is very easy to override the default

There are plenty of examples of that x:1 style, e.g.:
 - https://www.baeldung.com/groovy-maps
 - https://docs.groovy-lang.org/next/html/documentation/working-with-collections.html#Collections-Maps
 - https://stackoverflow.com/questions/12236743/map-with-key-as-string-and-value-as-list-in-groovy/12260635
 - http://grails.asia/groovy-map-tutorial
 - https://discuss.gradle.org/t/user-guide-list-and-map-literals/6318

**Comment by rkrisztian** [comment]
Thanks, I've checked the list:

* Baeldung's page shows plenty of inconsistencies, e.g. `[name:"Jerry", age: 42, city: "New York", hobby:"Singing"]` on the same line!
* Groovy's page: same
* 3rd is an example that was taken from the 4th link,
* Touché for the 4th link, maybe Grails is consistent then? Maybe 1 big follower of CodeNarc? Not sure, see this Grails cookbook: http://grails.asia/grails-example-application-simple-ajax-chat/ , again inconsistency
* People can't agree on coding styles.

Conclusions and counter-arguments:

* True, coding styles cannot be wrong, only easier or harder to read. And that's where things start to matter.
* If you are doing it "wrongly" at least do it consistently, that matters somewhat more.
* Coding style habits are often picked up from programming books/courses. That's how we learn languages too. We are only as good as our teachers. That can go wrong.
* Often people just look for recommended default settings, rather than looking for full customizations. => Some coding styles are introduced by blindly following tools the simplest way possible. A popular linting tool has the power of doing good or bad, just by what it does by default.
* The best coding styles follow English because we are very accustomed to that and hundreds of years polished it to a readable result.
* Often the lack of spaces are indicators of sloppy coding styles and programming habits too.

Regardless, yes I am probably still wrong at some points. I may be acting like a fanboy towards a certain style, which is unprofessional, sorry about that. And I have to accept that we are too late for this argument. So thanks for at least telling a reason, I appreciate that anyway.
