### ISSUE TITLE
[BUG] False positive NoTabCharacter and suppression doesn't work.

### ISSUE THREAD

**Issue by SergeyMormul** [CodeNarc/CodeNarc#644]
There is a test on the project I worked on with a multiple string literal represents a text, which has some tabs.
For the multiline string is big and long, LineLength is suppressed for a class. NoTabCharacter is also suppressed.
```groovy
@SuppressWarnings(['LineLength', 'NoTabCharacter'])
class TestClass { ... }
```
However, the rule is violated with the folloving message in console
```
[ant:codenarc] File: TestClass.groovy
[ant:codenarc]     Violation: Rule=NoTabCharacter P=3 Line=null Msg=[The tab character is not allowed in source files]
```
Dependencies:
Groovy: 2.5.14
Codenarc: 2.1.0

**Comment by chrismair** [comment]
**NoTabCharacter** is a file-based rule, rather than an AST-based rule, so the `@SuppressWarnings` annotation-based disablement does not work. I updated the online rule docs (in source control, but not yet on the web site) to reflect that.

I made a fix so that this rule returns the actual line number of the tab character in the violation.

With that fix, including a `// codenarc-disable NoTabCharacter` comment
somewhere above the violation will disable this rule. 

Will be available with CodeNarc 2.2.0.
