### ISSUE TITLE
Remove warning contains a GString-type expression: '${X_Y}'  GStringExpressionWithinString

### ISSUE THREAD

**Issue by sbollap1** [CodeNarc/CodeNarc#693]
I would like to escape this ${BLD_NUM} in the following code in targets, I am trying "\" but it doesn't remove the warning from the megalinter scan. How can I escape this and treat this as a string to avoid this warning.

```
 steps {
    //Wipe the workspace:
        wrappers {
            preBuildCleanup()
            sshAgent("${ABC}")
        }
        shell(readFileFromWorkspace("${path}/ssa.sh"))
        jobDsl {
            //escape within single quote
            targets('\${X_Y}/**/seed*.groovy')
        }
    }
}

```
  ****45    warning  The String '${X_Y}/**/seed*.groovy' contains a GString-type expression: '${X_Y}'  GStringExpressionWithinString****

I even tried the following with no luck

```
 jobDsl {
            //escape within single quote
            final SOURCE = '''
             def str8 = '\${X_Y}/**/seed*.groovy'
            '''
            targets(SOURCE)

...
```

@nvuillam thanks this thread says its fixed
[https://github.com/CodeNarc/CodeNarc/issues/188](https://github.com/CodeNarc/CodeNarc/issues/188)  however, iam still seeing this issue. appreciate some direction

**Comment by nvuillam** [comment]
@sbollap1 > MegaLinter embed npm-groovy-lint , which currently embeds CodeNarc 2.2.0 :)

And it seems that #188 has been solved loooong before CodeNarc 2.2.0...

If you think it's a false positive, I could just advise to add `/* groovylint-disable-line GStringExpressionWithinString */` at the end of your line

**Comment by nvuillam** [comment]
Only CodeNarc maintainers can help about this error, sorry :/

**Comment by chrismair** [comment]
Your code is not "wrong". This is one of those edge cases that pop up occasionally. It is difficult for CodeNarc to determine such cases where what looks like a GString expression is not really intended to be one.

Rather than add complexity to your code to work around the tool (CodeNarc), I'd be inclined to add the line comment to disable the rule as Nicolas suggested above, or just disable the rule for those files in your ruleset or codenarc.properties file.

If you really wanted to work around the false positive (violation), you could probably build those strings from parts to separate the '$' from the '{', e.g. something like `'\$' + '{X_Y}/**/seed*.groovy'`.

**Comment by chrismair** [comment]
Feel free to reopen if there is a CodeNarc issue.

**Comment by alexanderbazhenoff** [comment]
Also when I pass bash script via the string `for i in $(ls -d */); do echo ${i%%/}; done'` this warning me: `contains a GString-type expression: '${i%%/}'  GStringExpressionWithinString`. But actually this replacement in `i` variable is ok :)
