### ISSUE TITLE
Label indent - question 

### ISSUE THREAD

**Issue by dkubicki** [CodeNarc/CodeNarc#712]
Hi team, 

I'm looking for an option to check if the label indent level is correct.
Especially for Spock's label:

Failed

```    
       def "should sth"() {
        given:
        RevokeRequest request = aRevokeRequest()
```
Passed 

```    
       def "should sth"() {
        given:
             RevokeRequest request = aRevokeRequest()
```
Do we have such an option in the current set rules?

**Comment by chrismair** [comment]
CodeNarc does have an [Indentation](https://codenarc.org/codenarc-rules-formatting.html#indentation-rule) rule, but it does not check labels. And it looks like the labels are not exposed by the Groovy AST, so it is likely not practical to add such checks.

**Comment by xmac11** [comment]
Hello @chrismair @dkubicki , I came across the same issue which prevents using the `Indenation` rule with Spock, since the following syntax is considered a violation:

```groovy
def "should be true"() {
    expect:
        1 == 1
```

I've opened a PR addressing this (https://github.com/CodeNarc/CodeNarc/pull/729) 
Please have a look if it's something that you would want CodeNarc to support, otherwise feel free to close it.
