### ISSUE TITLE
Command line: how to send a list of files ?

### ISSUE THREAD

**Issue by nvuillam** [CodeNarc/CodeNarc#714]
I implemented the capability to receive a list of files as arguments of [npm-groovy-lint
](https://github.com/nvuillam/npm-groovy-lint/releases/tag/v10.0.0)

example: `npm-groovy-lint file1.groovy path/to/file2.groovy`

I convert that into a CodeNarc call and it works fine

example: `... -basedir=C:\\my-groovy-folder -includes=**/file1.groovy,**/path/to/file2.groovy -report=json:stdout`

Problems:
- Make an Ant-like pattern file search with wildcards to find files is useless to find files is useless, as files are already identified
- In case cwd is root folder, Ant-like pattern search browses all the hard disk
- It does not seem to work with absolute file paths

Questions:
- With current CodeNarc, is it possible to send a list of files as input ? If yes, how ?
- If it's not possible, do you think it would be complicated to make it possible ? Maybe with a new parameter -filelist ? (If yes, I could eventually make a PR)

Many thanks :)

**Comment by chrismair** [comment]
CodeNarc does not currently provide any other mechanism to specify a list of source files.

Is the problem you are attempting to address that there is not a single **basedir** -- i.e., the source files are spread across multiple file systems? Or perhaps that they are so deeply nested under **basedir** that the comma-separated list of relative filenames is just too big?

**Comment by nvuillam** [comment]
If found some workaround by getting the longest base folder of input files, to send in baseDir, but I think it could enhance again performances to not browse but just use sent files.

Do you know if there is a max length for -include ?

If someday I find the time to make a PR on CodeNarc allowing to send a list of files, would you accept it ?

**Comment by chrismair** [comment]
> Do you know if there is a max length for -include ?

I am not aware of any limitation other than the operating system/shell limit and Java Strings.

> If someday I find the time to make a PR on CodeNarc allowing to send a list of files, would you accept it ?

Yes, I think that would be acceptable. I assume that would be an optional parameter that if specified, would override "includes", "excludes", and I guess "basedir", too. I'm struggling to find a good name; my first thought was "sourceFiles", but the other "rulesetfiles" parameter specified a comma-separated file list, so that could be confusing. I don't know, "sourceFilesList"? I'll be interested to see what you come up with if you pursure that feature.
