### ISSUE TITLE
ConsecutiveBlankLines triggered for multiline strings

### ISSUE THREAD

**Issue by jochenberger** [CodeNarc/CodeNarc#720]
The following groovy File triggers a ConsecutiveBlankLines warning:
```groovy
def s = '''


'''
```
This should not be the case since the line breaks are part of a String.

**Comment by chrismair** [comment]
I agree this is a false positive. But this is a relatively simple file-based rule, rather than a Groovy AST-based rule, so it does not actually parse the code to determine the context of those consecutive blank lines. It is unlikely this will be fixed, but rather just treated as an edge case and known limitation. I'll update the doc for that rule to acknowledge that.

The workaround is to configure the rule to skip that file (using *doNotApplyToFileNames* or *doNotApplyToFilesMatching* rule properties). See [Standard Properties for Configuring Rules](https://codenarc.org/codenarc-configuring-rules.html#standard-properties-for-configuring-rules). Note that the class-based rule properties are not available on this rule.

**Comment by chrismair** [comment]
Closing. Feel free to reopen if more discussion is needed.
