### ISSUE TITLE
Support Multiple Library Imports in Jenksinfile

### ISSUE THREAD

**Issue by codezninja** [CodeNarc/CodeNarc#721]
So [Jenkinsfile recommends importing multiple shared libraries](https://www.jenkins.io/doc/book/pipeline/shared-libraries/#loading-libraries-dynamically) like so

```groovy
/* Accessing multiple libraries with one statement */
@Library(['my-shared-library', 'otherlib@abc1234']) _
```

npm-groovy-lint is by default failing for the `_` on 
* The variable [_] in class None is not used  UnusedVariable
* Variable named _ in class None does not match the pattern [a-z][a-zA-Z0-9]*  VariableName

Current workaround is to add `// groovylint-disable-line UnusedVariable, VariableName`. Could we by default add support for multiple library syntax support for these checks?

Cross posted from https://github.com/nvuillam/npm-groovy-lint/issues/246

**Comment by chrismair** [comment]
Another option is to configure your CodeNarc ruleset to disable those two rules for your Jenkins files: [Standard Properties for Configuring Rules](https://codenarc.org/codenarc-configuring-rules.html#standard-properties-for-configuring-rules).

In general, we try to avoid putting framework/tool-specific handling in the rules, since keeping up with all of those is not scalable or sustainable. (JUnit is one exception).

**Comment by chrismair** [comment]
Closing this issue; feel free to reopen if appropriate.
