### ISSUE TITLE
BooleanMethodReturnsNull should probably not be checked against Closures

### ISSUE THREAD

**Issue by s-ven** [CodeNarc/CodeNarc#762]
The following piece of raises `BooleanMethodReturnsNull` violation when it should really not be raising any violation

```groovy
class MyClass {
    void method() {
        if (foo()) {
            return
        }
        def closure = {
            return false
        }
        closure.call()
    }
}
```

Also, testing the following in groovyConsole, it is perfectly legit code

```groovy
def closure = {
    def foo = {}
    if (foo()) {
        return true
    } else {
        return 
    }
}
          
closure.call()
```

The above makes me wonder if CodeNarc should actually be visiting the contents of Closures and to a certain extent if it should also be ignoring void methods

**Comment by chrismair** [comment]
Apologies for the very delayed response.

I agree that the top code should not cause a violation, and seems to be a bug. We need to figure out how to have the closures analyzed in a separate/isolated context, rather than having the closure contents analyzed along with the rest of the method code and treated the same.

My take on the 2nd code example ("perfectly legit code") is that it is actually problematic. This rule was designed to catch that, since one path of the closure returns true and the other returns null.

I'm also considering how best to handle void methods.

**Comment by chrismair** [comment]
Fixed the original issue above, by analyzing contained closures within their own context. Not doing anything special for void methods at this point.
