### ISSUE TITLE
Question: Groovy Styl Guide

### ISSUE THREAD

**Issue by bbrueche** [CodeNarc/CodeNarc#780]
Is there a Groovy Coding Style Guide that you are trying to follow? That's different than specifying the rules [here] (https://codenarc.org/codenarc-rules-convention.html). I'm looking for a recommendation sheet for Groovy developers on how to properly name labels and classes to match the default coding style implemented. If there is such a thing, I would like to refer to this document when developers ask for guidance.

**Comment by chrismair** [comment]
The CodeNarc "convention" ruleset is just a somewhat-arbitrary grouping of some rules that tend to be stylistic or controversial, rather than enforcing right vs wrong or good vs bad. They are just a tiny fraction of available rules, so they are not meant to imply any kind of guide.

The [Groovy Style Guide](https://groovy-lang.org/style-guide.html) is helpful, although that is more about language features rather than style.

The original CodeNarc rules and some of the styles and conventions they enforce were influenced by looking at the Groovy project source code, as well as other projects such as Grails. They are also heavily influenced by the rulesets of Java tools such as PMD, Checkstyle and FindBugs. But most of those early rules go back 10+ years, so some drift is inevitable.

I do see some articles/posts about Groovy style guides doing a Google search.

**Comment by bbrueche** [comment]
Hi Chris,

Thanks for your reply. We have adopted the Google Java Style Guide and adjusted it to Groovy language and our needs. That looks to work for us, harmonizing different Groovy projects across the company.

Thanks,
Bjoern
