### ISSUE TITLE
Improve HTML Report Format

### ISSUE THREAD

**Issue by influenza** [CodeNarc/CodeNarc#92]
There are a number of questions about the results of a codenarc run that are difficult to answer using the current HTML report format. 

Specifically:

* It is difficult to quickly get a grasp on where the priority 1 issues are. You cannot do a simple search, as the search string would be '1'. There is not a section that summarizes issues by priority. This means one must scroll through the entire document (a potentially lengthy artifact) scanning for red items.
* Determining the "worst offender" file is not possible in the HTML report format.
* Ditto with determining the most common violation. This would be useful, for instance, to let a developer know that running a well-crafted awk or sed command on the codebase would resolve most of the violations.
* Related to the above, violations grouped by rule.

While I understand the above information could be gleaned from processing the xml output, the HTML report really should be more useful. Given that the HTML report is intended for human consumption, why not use some Javascript to provide a way to easily sort and display the violation data?

**Comment by tedder** [comment]
This would be better than grepping the text version. I had parsed the html version to get information but it's really painful- it's been a while since I was doing it, but simply parsing the html in Python took 60+ seconds.

**Comment by chrismair** [comment]
Thanks for the feedback. I can see the value in being able to sort by different fields/aspects.

Were you envisioning a restructured HTML report with everything in one table, with sortable column headers? That might be a very wide table. Pull requests are welcome, though I think I'd prefer to create a new XxxHtmlReportWriter class, rather than radically restructure the existing report.

Alternatively, I think it would be pretty straightforward to introduce separate relatively simple report classes, each specialized to sort by a different aspect: by rule, by priority, by file.

As a side not, you can accomplish *part* of one of your use cases by producing an HTML report with the *maxPriority* property set to 1 or 2, but I know that is only a partial solution to only one of the use cases.

Chris

**Comment by influenza** [comment]
Hi Chris, thanks a lot for your response! The 'maxPriority' property will certainly be a useful stop-gap. I don't have any design in particular in mind, just the questions I'd like the report to help me answer.

I hope to have some time to work on this in the next week or so.

Regards!

**Comment by chrismair** [comment]
This is now available in CodeNarc 0.24.

There is a new SortableHtmlReportWriter, report type "sortable". Sort by rules (with the most violations) and files (with the most violations), as well as rule name and rule priority.
